name: defake
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.3.0
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - cuda-version=11.3
  - cudatoolkit=11.3.1
  - cudnn=8.9.7.29
  - cupti=11.3.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - entrypoints=0.4
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - ffmpeg=5.0.1
  - freetype=2.13.3
  - future=1.0.0
  - gmp=6.3.0
  - gnutls=3.6.15
  - icu=70.1
  - idna=3.7
  - importlib-metadata=8.7.0
  - intel-openmp=2021.4.0
  - ipykernel=6.29.5
  - ipython=8.36.0
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.17
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmagma=2.7.2
  - libmagma_sparse=2.7.2
  - libnsl=2.0.1
  - libpciaccess=0.18
  - libpng=1.6.47
  - libprotobuf=3.20.3
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvpx=1.11.0
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.10.2
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - magma=2.7.2
  - matplotlib-inline=0.1.7
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - ninja=1.12.1
  - numpy=1.23.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.5.0
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=25.1.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.10.17
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - readline=8.2
  - requests=2.32.3
  - scipy=1.13.1
  - setuptools=80.8.0
  - six=1.16.0
  - sqlite=3.49.2
  - stack_data=0.6.3
  - svt-av1=1.1.0
  - tk=8.6.13
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - tzdata=2025b
  - urllib3=2.3.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - x264=1!161.3030
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.7.0
      - clip==1.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - diffusers==0.33.1
      - filelock==3.13.1
      - fonttools==4.58.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - hf-xet==1.1.2
      - huggingface-hub==0.32.0
      - jinja2==3.1.4
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - natsort==8.4.0
      - networkx==3.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - pycocotools==2.0.8
      - pyparsing==3.2.3
      - regex==2024.11.6
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - tokenizers==0.19.1
      - torch==2.4.1+cu121
      - torchaudio==2.4.1+cu121
      - torchvision==0.19.1+cu121
      - tqdm==4.67.1
      - transformers==4.43.0
      - triton==3.0.0
